#!/usr/bin/env bash
# Install nginx web server
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx Full'
chown -R www-data /var/www/html/
echo "Holberton School for the win!" > /var/www/html/index.html
service nginx start
