#!/usr/bin/env bash
# Redirect to another page.
sudo apt-get -y update
sudo apt-get -y install nginx
sudo chmod 777 /var/www/html/index.nginx-debian.html
sudo echo "Holberton School"  | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx stop
sudo chmod 777 /etc/nginx/sites-available/default
sudo sed -i "\\\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n" /etc/nginx/sites-available/default
sudo service nginx restart
