#!/usr/bin/env bash
# set page not found
sudo apt-get -y update
sudo apt-get -y install nginx
sudo chmod 777 /var/www/html/index.nginx-debian.html
sudo echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo service nginx stop
sudo chmod 777 /etc/nginx/sites-available/default
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sudo sed -i "/listen 80 default_server/a error_page 404 /custom_404.html; location = /custom_404.html { root /var/www/html; internal; }" /etc/nginx/sites-available/default
sudo service nginx restart
