#!/usr/bin/env bash
# Install Nginx that its HTTP response contains a custom header
apt-get -y update
apt-get -y upgrade
apt-get -y install nginx
sed -i "11i\\\tadd_header X-Served-By \$HOSTNAME;" /etc/nginx/sites-available/default
echo "Holberton School" > /usr/share/nginx/html/index.html
sudo service nginx start
