#!/usr/bin/env bash
# install load balancer
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y update
sudo apt-get install haproxy=2.0.\*
sudo echo -e "\nlisten www" >> /etc/haproxy/haproxy.cfg
sudo echo -e "\tbind :80" >> /etc/haproxy/haproxy.cfg
sudo echo -e "\tbalance roundrobin" >> /etc/haproxy/haproxy.cfg
sudo echo -e "\tserver 1283-web-01 35.185.87.254 check" >> /etc/haproxy/haproxy.cfg
sudo echo -e "\tserver 1283-web-02 52.72.127.245 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
