#!/usr/bin/env bash
# Fix Nginx listening on port 80 of all the server’s active IPv4 IPs
sudo sed -i 's/8080/80/'  /etc/nginx/sites-enabled/default
sudo sed -i 's/8080/80/' /etc/nginx/sites-available/default
service nginx restart
