#!/usr/bin/env bash
# Fix Nginx listening on port 80 of all the server’s active IPv4 IPs
sudo sed "s/listen 8080/listen 80/"  "/etc/nginx/sites-enabled/default"
sudo sed "s/listen [::]/# listen [::]" "/etc/nginx/sites-enabled/default"
service nginx restart
