#!/bin/bash
# Change your home IP localhost resolves to 127.0.0.2
#               facebook.com resolves to 8.8.8.8

sudo sed -i "s/127.0.0.1/127.0.0.2/" /etc/hosts
sudo echo "" >> /etc/hosts
sudo echo "8.8.8.8 facebook.com" >> /etc/hosts