#!/user/bin/env bash
# Run Nginx as nginx  and listen on port 8080
sudo service nginx stop
sudo chmod 644 /etc/nginx/nginx.conf
sudo sed -i "2i user nginx;" /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/" /etc/nginx/sites-enabled/default
# sudo chmod 000 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
